// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9-__scT7-CaKqn3A0iq9oAGOPLXZJIh0',
    appId: '1:402188709733:web:75303163456388dfdcbb8c',
    messagingSenderId: '402188709733',
    projectId: 'okan-yazilim-ajansi',
    authDomain: 'okan-yazilim-ajansi.firebaseapp.com',
    storageBucket: 'okan-yazilim-ajansi.firebasestorage.app',
    measurementId: 'G-Y2SKVLZW68',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDusziP4YEJ-fGPUcTVLbuD5HozqfIqNSA',
    appId: '1:402188709733:android:a0f6e1dfe0a0f291dcbb8c',
    messagingSenderId: '402188709733',
    projectId: 'okan-yazilim-ajansi',
    storageBucket: 'okan-yazilim-ajansi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6NZDa7Vzz-XGexoKPcV4Auj4Rb0iecm0',
    appId: '1:402188709733:ios:52368f985c5ea00adcbb8c',
    messagingSenderId: '402188709733',
    projectId: 'okan-yazilim-ajansi',
    storageBucket: 'okan-yazilim-ajansi.firebasestorage.app',
    iosBundleId: 'com.example.okanyazilim2',
  );
}
